[package]
name = "simplebase-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
simplebase = { path = "../../languages/simplebase" }
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
serde-wasm-bindgen = "0.6.5"
serde = "1.0.219"
