[package]
name = "simplelambdamu"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
nom_locate = "5.0.0"
num = "0.4.3"
rstest = "0.25.0"
rustyline = "15.0.0"
typst = "0.13.1"
typst-library = "0.13.1"
typst-svg = "0.13.1"
typst-syntax = "0.13.1"
typst-utils = "0.13.1"
